CREATE TABLE IF NOT EXISTS erblog (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    imageBase64  MEDIUMTEXT  NULL
);